import os
import digikey
from digikey.v3.productinformation import KeywordSearchRequest

os.environ['DIGIKEY_CLIENT_ID'] = ''
os.environ['DIGIKEY_CLIENT_SECRET'] = ''
os.environ['DIGIKEY_CLIENT_SANDBOX'] = 'True'
os.environ['DIGIKEY_STORAGE_PATH'] = '.'

# Query product number
# dkpn = '296-6501-1-ND'
# part = digikey.product_details(dkpn)

# Search for parts 
search_request = KeywordSearchRequest(keywords='transistor', record_count=1)
result = digikey.keyword_search(body=search_request)
print(result)

# {'exact_digi_key_product': None,
#  'exact_manufacturer_products': [],
#  'exact_manufacturer_products_count': 0,
#  'filter_options': [{'parameter': 'Manufacturer',
#                      'parameter_id': -1,
#                      'values': [{'value': 'Panasonic Electronic Components',
#                                  'value_id': '10'}]},
#                     {'parameter': 'Packaging',
#                      'parameter_id': 7,
#                      'values': [{'value': 'Bulk', 'value_id': '3'}]},
#                     {'parameter': 'Series',
#                      'parameter_id': -5,
#                      'values': [{'value': 'NHG', 'value_id': '189'}]},
#                     {'parameter': 'Part Status',
#                      'parameter_id': 1989,
#                      'values': [{'value': 'Active', 'value_id': '0'}]},
#                     {'parameter': 'Capacitance',
#                      'parameter_id': 13,
#                      'values': [{'value': '1000µF', 'value_id': '65'}]},
#                     {'parameter': 'Tolerance',
#                      'parameter_id': 3,
#                      'values': [{'value': '±20%', 'value_id': '5'}]},
#                     {'parameter': 'Voltage Rating',
#                      'parameter_id': 63,
#                      'values': [{'value': '35V', 'value_id': '371'}]},
#                     {'parameter': 'ESR (Equivalent Series Resistance)',
#                      'parameter_id': 724,
#                      'values': [{'value': '-', 'value_id': '233'}]},
#                     {'parameter': 'Lifetime @ Temp.',
#                      'parameter_id': 725,
#                      'values': [{'value': '2000 Hrs @ 105°C',
#                                  'value_id': '7'}]},
#                     {'parameter': 'Operating Temperature',
#                      'parameter_id': 252,
#                      'values': [{'value': '-55°C ~ 105°C', 'value_id': '42'}]},
#                     {'parameter': 'Polarization',
#                      'parameter_id': 52,
#                      'values': [{'value': 'Polar', 'value_id': '14'}]},
#                     {'parameter': 'Applications',
#                      'parameter_id': 405,
#                      'values': [{'value': 'General Purpose',
#                                  'value_id': '19'}]},
#                     {'parameter': 'Ripple Current',
#                      'parameter_id': 1317,
#                      'values': [{'value': '810mA @ 120Hz',
#                                  'value_id': '3670'}]},
#                     {'parameter': 'Impedance',
#                      'parameter_id': 60,
#                      'values': [{'value': '-', 'value_id': '89'}]},
#                     {'parameter': 'Lead Spacing',
#                      'parameter_id': 508,
#                      'values': [{'value': '0.197" (5.00mm)', 'value_id': '4'}]},
#                     {'parameter': 'Size / Dimension',
#                      'parameter_id': 46,
#                      'values': [{'value': '0.492" Dia (12.50mm)',
#                                  'value_id': '13984'}]},
#                     {'parameter': 'Height - Seated (Max)',
#                      'parameter_id': 1500,
#                      'values': [{'value': '0.866" (22.00mm)',
#                                  'value_id': '273'}]},
#                     {'parameter': 'Surface Mount Land Size',
#                      'parameter_id': 884,
#                      'values': [{'value': '-', 'value_id': '4'}]},
#                     {'parameter': 'Mounting Type',
#                      'parameter_id': 69,
#                      'values': [{'value': 'Through Hole', 'value_id': '80'}]},
#                     {'parameter': 'Package / Case',
#                      'parameter_id': 16,
#                      'values': [{'value': 'Radial, Can',
#                                  'value_id': '11811'}]}],
#  'limited_taxonomy': {'children': [{'children': [{'children': [],
#                                                   'new_product_count': 0,
#                                                   'parameter': 'Categories',
#                                                   'parameter_id': -8,
#                                                   'product_count': 1,
#                                                   'value': 'Aluminum '
#                                                            'Capacitors',
#                                                   'value_id': '58'}],
#                                     'new_product_count': 0,
#                                     'parameter': 'Categories',
#                                     'parameter_id': -8,
#                                     'product_count': 1,
#                                     'value': 'Capacitors',
#                                     'value_id': '3'}],
#                       'new_product_count': 0,
#                       'parameter': 'Categories',
#                       'parameter_id': -8,
#                       'product_count': 1,
#                       'value': 'Out of Bounds',
#                       'value_id': '0'},
#  'products': [{'alternate_packaging': [],
#                'category': None,
#                'date_last_buy_chance': None,
#                'detailed_description': None,
#                'digi_key_part_number': 'P5555-ND',
#                'dk_plus_restriction': False,
#                'export_control_class_number': None,
#                'family': None,
#                'htsus_code': None,
#                'lead_status': 'Lead Free',
#                'manufacturer': {'parameter': '',
#                                 'parameter_id': 0,
#                                 'value': 'Panasonic Electronic Components',
#                                 'value_id': '10'},
#                'manufacturer_lead_weeks': '14 weeks',
#                'manufacturer_page_url': 'https://www.digikey.com/en/supplier-centers/p/panasonic',
#                'manufacturer_part_number': 'ECA-1VHG102',
#                'manufacturer_public_quantity': 0,
#                'marketplace': False,
#                'minimum_order_quantity': 1,
#                'moisture_sensitivity_level': '',
#                'non_stock': False,
#                'packaging': {'parameter': 'Packaging',
#                              'parameter_id': 7,
#                              'value': 'Bulk',
#                              'value_id': '3'},
#                'parameters': [{'parameter': 'Packaging',
#                                'parameter_id': 7,
#                                'value': 'Bulk',
#                                'value_id': '3'},
#                               {'parameter': 'Part Status',
#                                'parameter_id': 1989,
#                                'value': 'Active',
#                                'value_id': '0'},
#                               {'parameter': 'Capacitance',
#                                'parameter_id': 13,
#                                'value': '1000µF',
#                                'value_id': '65'},
#                               {'parameter': 'Tolerance',
#                                'parameter_id': 3,
#                                'value': '±20%',
#                                'value_id': '5'},
#                               {'parameter': 'Voltage Rating',
#                                'parameter_id': 63,
#                                'value': '35V',
#                                'value_id': '371'},
#                               {'parameter': 'ESR (Equivalent Series '
#                                             'Resistance)',
#                                'parameter_id': 724,
#                                'value': '-',
#                                'value_id': '233'},
#                               {'parameter': 'Lifetime @ Temp.',
#                                'parameter_id': 725,
#                                'value': '2000 Hrs @ 105°C',
#                                'value_id': '7'},
#                               {'parameter': 'Operating Temperature',
#                                'parameter_id': 252,
#                                'value': '-55°C ~ 105°C',
#                                'value_id': '42'},
#                               {'parameter': 'Polarization',
#                                'parameter_id': 52,
#                                'value': 'Polar',
#                                'value_id': '14'},
#                               {'parameter': 'Applications',
#                                'parameter_id': 405,
#                                'value': 'General Purpose',
#                                'value_id': '19'},
#                               {'parameter': 'Ripple Current',
#                                'parameter_id': 1317,
#                                'value': '810mA @ 120Hz',
#                                'value_id': '3670'},
#                               {'parameter': 'Impedance',
#                                'parameter_id': 60,
#                                'value': '-',
#                                'value_id': '89'},
#                               {'parameter': 'Lead Spacing',
#                                'parameter_id': 508,
#                                'value': '0.197" (5.00mm)',
#                                'value_id': '4'},
#                               {'parameter': 'Size / Dimension',
#                                'parameter_id': 46,
#                                'value': '0.492" Dia (12.50mm)',
#                                'value_id': '13984'},
#                               {'parameter': 'Height - Seated (Max)',
#                                'parameter_id': 1500,
#                                'value': '0.866" (22.00mm)',
#                                'value_id': '273'},
#                               {'parameter': 'Surface Mount Land Size',
#                                'parameter_id': 884,
#                                'value': '-',
#                                'value_id': '4'},
#                               {'parameter': 'Mounting Type',
#                                'parameter_id': 69,
#                                'value': 'Through Hole',
#                                'value_id': '80'},
#                               {'parameter': 'Package / Case',
#                                'parameter_id': 16,
#                                'value': 'Radial, Can',
#                                'value_id': '11811'}],
#                'primary_datasheet': 'https://industrial.panasonic.com/cdbs/www-data/pdf/RDF0000/ABA0000C1215.pdf',
#                'primary_photo': 'http://media.digikey.com/Photos/Panasonic%20Photos/NHG12-SERIES.jpg',
#                'primary_video': '',
#                'product_description': 'CAP ALUM 1000UF 20% 35V RADIAL',
#                'product_status': 'Active',
#                'product_url': '/product-detail/en/panasonic-electronic-components/ECA-1VHG102/P5555-ND/245154',
#                'quantity_available': 8888,
#                'quantity_on_order': 0,
#                'reach_status': None,
#                'ro_hs_status': 'RoHS Compliant',
#                'series': {'parameter': 'Series',
#                           'parameter_id': -5,
#                           'value': 'NHG',
#                           'value_id': '189'},
#                'standard_pricing': [{'break_quantity': 1,
#                                      'total_price': 0.78,
#                                      'unit_price': 0.78},
#                                     {'break_quantity': 10,
#                                      'total_price': 5.93,
#                                      'unit_price': 0.593},
#                                     {'break_quantity': 25,
#                                      'total_price': 13.12,
#                                      'unit_price': 0.5248},
#                                     {'break_quantity': 50,
#                                      'total_price': 24.64,
#                                      'unit_price': 0.4928},
#                                     {'break_quantity': 100,
#                                      'total_price': 42.43,
#                                      'unit_price': 0.4243},
#                                     {'break_quantity': 250,
#                                      'total_price': 95.81,
#                                      'unit_price': 0.38324},
#                                     {'break_quantity': 500,
#                                      'total_price': 164.25,
#                                      'unit_price': 0.3285},
#                                     {'break_quantity': 1000,
#                                      'total_price': 282.88,
#                                      'unit_price': 0.28288},
#                                     {'break_quantity': 5000,
#                                      'total_price': 1254.7,
#                                      'unit_price': 0.25094}],
#                'supplier_direct_ship': False,
#                'tariff_description': None,
#                'unit_price': 78000.0}],
#  'products_count': 1,
#  'search_locale_used': {'currency': 'USD',
#                         'language': 'en',
#                         'ship_to_country': '',
#                         'site': 'US'}}
